services:
  mongo:
    image: mongo:7
    container_name: users-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-api-service:
    build:
      context: .
      dockerfile: services/users-api-service/Dockerfile
    container_name: users-api-service
    depends_on:
      - mongo
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}  
    ports:
      - "8081:8081"

  profile-service:
    build:
      context: .
      dockerfile: services/profile-service/Dockerfile
    container_name: profile-service
    depends_on:
      - users-api-service
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}  
    ports:
      - "8080:8080"

  mobile-api-service:
    build:
      context: .
      dockerfile: services/mobile-api-service/Dockerfile
    container_name: mobile-api-service
    depends_on:
      - users-api-service
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=api-key=${NEW_RELIC_LICENSE_KEY}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}  
    ports:
      - "8082:8082"

volumes:
  mongo_data:
